name: Build and Deploy Jekyll Site

on:
  repository_dispatch:
    types: [trigger-build]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }} # Use PAT to allow pushing to gh-pages
          ref: main
          fetch-depth: 0

      - name: 💎 Setup Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Updated to support bundler 2.7.1
          bundler-cache: true

      - name: 🔨 Build the site
        run: bundle exec jekyll build  --config _config.yml
        env:
          JEKYLL_ENV: production

      - name: 🗜️ Compress assets
        run: |
          # 压缩HTML文件
          find _site -name "*.html" -exec gzip -k {} \;
          # 压缩CSS文件
          find _site -name "*.css" -exec gzip -k {} \;
          # 压缩JS文件
          find _site -name "*.js" -exec gzip -k {} \;
          # 压缩XML文件
          find _site -name "*.xml" -exec gzip -k {} \;

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./_site
          # Optional: if you have a custom domain
          # cname: your.domain.com
